language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

sudo: false

before_script:
  - wget -nc http://getcomposer.org/composer.phar
  - php composer.phar update phpunit/phpunit
  - php composer.phar install

script: vendor/bin/phpunit --configuration phpunit.xml.dist
