name: Test Suite
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ "8.0", "8.1"]
    name: PHP ${{matrix.php }} Unit Test
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - name: Install Dependencies
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: composer install
      - name: Run Script
        run: vendor/bin/phpunit

  style:
    runs-on: ubuntu-latest
    name: PHP Style Check
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"
      - name: Run Script
        run: |
          composer require friendsofphp/php-cs-fixer
          vendor/bin/php-cs-fixer fix --diff --dry-run .
          vendor/bin/php-cs-fixer fix --rules=native_function_invocation --allow-risky=yes --diff src

  staticanalysis:
    runs-on: ubuntu-latest
    name: PHPStan Static Analysis
    steps:
    - uses: actions/checkout@v2
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
    - name: Run Script
      run: |
        composer global require phpstan/phpstan
        ~/.composer/vendor/bin/phpstan analyse src
